# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'uji.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc 
from PyQt5.QtWidgets import QTableWidgetItem

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(579, 457)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 91, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_npm = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_npm.setObjectName("label_npm")
        self.verticalLayout.addWidget(self.label_npm)
        self.label_nama = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_nama.setObjectName("label_nama")
        self.verticalLayout.addWidget(self.label_nama)
        self.label_kelas = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_kelas.setObjectName("label_kelas")
        self.verticalLayout.addWidget(self.label_kelas)
        self.label_jurusan = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_jurusan.setObjectName("label_jurusan")
        self.verticalLayout.addWidget(self.label_jurusan)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(90, 0, 221, 161))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_2.addWidget(self.lineEdit_2)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_2.addWidget(self.lineEdit)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_2.addWidget(self.lineEdit_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_2.addWidget(self.lineEdit_4)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_2.addWidget(self.lineEdit_3)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 170, 421, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonInsert = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonInsert.setObjectName("pushButtonInsert")
        self.horizontalLayout.addWidget(self.pushButtonInsert)
        self.pushButtonUpdate = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonUpdate.setObjectName("pushButtonUpdate")
        self.horizontalLayout.addWidget(self.pushButtonUpdate)
        self.pushButtonDelete = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.horizontalLayout.addWidget(self.pushButtonDelete)
        self.pushButtonLoad = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        self.horizontalLayout.addWidget(self.pushButtonLoad)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(9, 219, 501, 171))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget_3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(330, 140, 171, 16))
        self.label_6.setObjectName("label_6")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 410, 491, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_2.addWidget(self.lineEdit_6)
        self.pushButtonSearch = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.horizontalLayout_2.addWidget(self.pushButtonSearch)


        self.pushButtonLoad.clicked.connect(self.loadmahasiswa)
        self.pushButtonInsert.clicked.connect(self.insertmahasiswa)
        self.tableWidget.clicked.connect(self.handleCellClick)
        self.pushButtonUpdate.clicked.connect(self.updatemahasiswa)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def loadmahasiswa(self):
        try:
            mydb = mc.connect(
                host ="localhost",
                user ="root",
                password ="",
                database ="db_kampus"
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT * FROM mahasiswa ORDER BY NPM ASC")
            result = mycursor.fetchall()
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number,column_number, QTableWidgetItem(str(data)))
            self.label_6.setText("Data Kategori Berhasil Ditampilkan")
        except mc.Error as err:
            self.label_6.setText("Data Kategori Gagal DiLoad")

    def handleCellClick(self, row, column):
        try:
            npmkat = self.tableWidget.item(row, 0).text()
            namakat = self.tableWidget.item(row, 1).text()
            kelaskat = self.tableWidget.item(row, 2).text()
            jurusankat = self.tableWidget.item(row, 3).text()
            ttlkat = self.tableWidget.item(row, 4).text()
            self.lineEditId_2.setText(npmkat)
            self.lineEdit.setText(namakat)
            self.lineEdit_5.setText(kelaskat)
            self.lineEdit_4.setText(jurusankat)
            self.lineEdit_3.setText(ttlkat)
            self.label_6.setText("Data Kategori Ditampilkan di Input")
        except Exception as e:
            self.label_6.setText("Data Kategori Gagal Ditampilkan di Input")
            

    def insertmahasiswa(self):
        try:
            mydb = mc.connect(
                host ="localhost",
                user ="root",
                password ="",
                database ="db_kampus"
            )
            cursor = mydb.cursor()
            npmkat = self.lineEdit_2.text()
            namakat = self.lineEdit.text()
            kelaskat = self.lineEdit_5.text()
            jurusankat = self.lineEdit_4.text()
            ttlkat = self.lineEdit_3.text()
            sql = "INSERT INTO mahasiswa (npm, nama, kelas, jurusan, tgl_lahir) VALUES (%s,%s,%s,%s,%s)"
            val = (npmkat,namakat,kelaskat,jurusankat,ttlkat)
            cursor.execute(sql,val)
            mydb.commit()
            self.label_6.setText("Data Kategori Berhasil Disimpan")
            self.lineEdit_2.setText("")
            self.lineEdit.setText("")
            self.lineEdit_5.setText("")
            self.lineEdit_4.setText("")
            self.lineEdit_3.setText("")
        except mc.Error as e:
            self.label_6.setText("Data Kategori Gagal Disimpan")

    def updatemahasiswa(self):
        try:
            mydb = mc.connect(
                host ="localhost",
                user ="root",
                password ="",
                database ="db_kampus"
            )
            cursor = mydb.cursor()
            npmkat = self.lineEdit_2.text()
            namakat = self.lineEdit.text()
            sql = "UPDATE mahasiswa SET nama = %s WHERE npm=%s"
            val = (npmkat,namakat)
            cursor.execute(sql,val)
            mydb.commit()
            self.label_6.setText("Data Kategori Berhasil Diubah")
            self.lineEdit_2.setText("")
            self.lineEdit.setText("")
        except mc.Error as e:
            self.label_6.setText("Data Kategori Gagal Diubah")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_npm.setText(_translate("Form", "NPM"))
        self.label_nama.setText(_translate("Form", "NAMA"))
        self.label_kelas.setText(_translate("Form", "KELAS"))
        self.label_jurusan.setText(_translate("Form", "JURUSAN"))
        self.label_5.setText(_translate("Form", "TTL"))
        self.pushButtonInsert.setText(_translate("Form", "INSERT"))
        self.pushButtonUpdate.setText(_translate("Form", "UPDATE"))
        self.pushButtonDelete.setText(_translate("Form", "DELETE"))
        self.pushButtonLoad.setText(_translate("Form", "LOADDATA"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "NPM"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "NAMA"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "KELAS"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "JURUSAN"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "TTL"))
        self.label_6.setText(_translate("Form", "TextLabel"))
        self.pushButtonSearch.setText(_translate("Form", "SEARCH"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
