# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'product.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import mysql.connector as mc 
from PyQt5.QtWidgets import QTableWidgetItem


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(531, 454)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(320, 140, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(30, 410, 491, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lineEditsearch = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.lineEditsearch.setObjectName("lineEditsearch")
        self.horizontalLayout_2.addWidget(self.lineEditsearch)
        self.pushButtonSearch = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.pushButtonSearch.setObjectName("pushButtonSearch")
        self.horizontalLayout_2.addWidget(self.pushButtonSearch)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(19, 219, 501, 171))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget_3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(100, 0, 221, 171))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lineEditid = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditid.setObjectName("lineEditid")
        self.verticalLayout_2.addWidget(self.lineEditid)
        self.lineEditbarkode = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditbarkode.setObjectName("lineEditbarkode")
        self.verticalLayout_2.addWidget(self.lineEditbarkode)
        self.lineEditname = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditname.setObjectName("lineEditname")
        self.verticalLayout_2.addWidget(self.lineEditname)
        self.lineEditkategori = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditkategori.setObjectName("lineEditkategori")
        self.verticalLayout_2.addWidget(self.lineEditkategori)
        self.lineEditqty = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditqty.setObjectName("lineEditqty")
        self.verticalLayout_2.addWidget(self.lineEditqty)
        self.lineEditharga = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.lineEditharga.setObjectName("lineEditharga")
        self.verticalLayout_2.addWidget(self.lineEditharga)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 91, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.labelid = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelid.setObjectName("labelid")
        self.verticalLayout.addWidget(self.labelid)
        self.labelbarkode = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelbarkode.setObjectName("labelbarkode")
        self.verticalLayout.addWidget(self.labelbarkode)
        self.labelname = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelname.setObjectName("labelname")
        self.verticalLayout.addWidget(self.labelname)
        self.labelkategori = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelkategori.setObjectName("labelkategori")
        self.verticalLayout.addWidget(self.labelkategori)
        self.labelqty = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelqty.setObjectName("labelqty")
        self.verticalLayout.addWidget(self.labelqty)
        self.labelharga = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.labelharga.setObjectName("labelharga")
        self.verticalLayout.addWidget(self.labelharga)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 170, 421, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonInsert = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonInsert.setObjectName("pushButtonInsert")
        self.horizontalLayout.addWidget(self.pushButtonInsert)
        self.pushButtonUpdate = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonUpdate.setObjectName("pushButtonUpdate")
        self.horizontalLayout.addWidget(self.pushButtonUpdate)
        self.pushButtonDelete = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.horizontalLayout.addWidget(self.pushButtonDelete)
        self.pushButtonLoad = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        self.horizontalLayout.addWidget(self.pushButtonLoad)

        self.pushButtonLoad.clicked.connect(self.loadproduct)
        self.pushButtonInsert.clicked.connect(self.insertproduct)
        self.tableWidget.clicked.connect(self.handleCellClick)
        self.pushButtonUpdate.clicked.connect(self.updateproduct)
        self.pushButtonDelete.clicked.connect(self.deleteproduct)
        self.pushButtonSearch.clicked.connect(self.searchingproduct)


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def loadproduct(self):
        try:
            mydb = mc.connect(
                host ="localhost",
                user ="root",
                password ="",
                database ="db_penjualanbaru"
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT * FROM product ORDER BY id ASC")
            result = mycursor.fetchall()
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number,column_number, QTableWidgetItem(str(data)))
            self.label_6.setText("Data Product Berhasil Ditampilkan")
        except mc.Error as err:
            self.label_6.setText("Data Product Gagal DiLoad")

    def handleCellClick(self, item):
        try:
            row = item.row()
            column = item.column()
            
            # Ambil data berdasarkan baris dan kolom
            idkat = self.tableWidget.item(row, 0).text()
            barkodekat = self.tableWidget.item(row, 1).text()
            namekat = self.tableWidget.item(row, 2).text()
            kategorikat = self.tableWidget.item(row, 3).text()
            qtykat = self.tableWidget.item(row, 4).text()
            hargakat = self.tableWidget.item(row, 5).text()

            # Set data ke LineEdit
            self.lineEditid.setText(idkat)
            self.lineEditbarkode.setText(barkodekat)
            self.lineEditname.setText(namekat)
            self.lineEditkategori.setText(kategorikat)
            self.lineEditqty.setText(qtykat)
            self.lineEditharga.setText(hargakat)
            self.label_6.setText("Data Kategori Ditampilkan di Input")
        except Exception as e:
            self.label_6.setText(f"Data Kategori Gagal Ditampilkan di Input: {e}")



    def insertproduct(self):
        try:
            mydb = mc.connect(
                host ="localhost",
                user ="root",
                password ="",
                database ="db_penjualanbaru"
            )
            cursor = mydb.cursor()
            idkat = self.lineEditid.text()
            barkodekat = self.lineEditbarkode.text()
            namekat = self.lineEditname.text()
            kategorikat = self.lineEditkategori.text()
            qtykat = self.lineEditqty.text()
            hargatkat = self.lineEditharga.text()
            sql = "INSERT INTO product (id, barkode, name, kategori, qty, harga) VALUES (%s,%s,%s,%s,%s,%s)"
            val = (idkat,barkodekat,namekat,kategorikat,qtykat,hargatkat)
            cursor.execute(sql,val)
            mydb.commit()
            self.label_6.setText("Data Product Berhasil Disimpan")
            self.lineEditid.setText("")
            self.lineEditbarkode.setText("")
            self.lineEditname.setText("")
            self.lineEditkategori.setText("")
            self.lineEditqty.setText("")
            self.lineEditharga.setText("")
        except mc.Error as e:
            self.label_6.setText("Data Product Gagal Disimpan")

    def updateproduct(self):
        try:
            mydb = mc.connect(
                host ="localhost",
                user ="root",
                password ="",
                database ="db_penjualanbaru"
            )
            cursor = mydb.cursor()
            idkat = self.lineEditid.text()
            barkodekat = self.lineEditbarkode.text()
            namekat = self.lineEditname.text()
            kategorikat = self.lineEditkategori.text()
            qtykat = self.lineEditqty.text()
            hargakat = self.lineEditharga.text()
            sql = "UPDATE product SET barkode = %s, name = %s, kategori = %s, qty = %s, harga = %s WHERE id = %s"
            val = (barkodekat,namekat,kategorikat,qtykat,hargakat,idkat)
            cursor.execute(sql,val)
            mydb.commit()
            self.label_6.setText("Data Product Berhasil Diubah")
            self.lineEditid.setText("")
            self.lineEditbarkode.setText("")
            self.lineEditname.setText("")
            self.lineEditkategori.setText("")
            self.lineEditqty.setText("")
            self.lineEditharga.setText("")
        except mc.Error as e:
            self.label_6.setText("Data Product Gagal Diubah")

    def deleteproduct(self):
        try:
            mydb = mc.connect(
                host ="localhost",
                user ="root",
                password ="",
                database ="db_penjualanbaru"
            )
            cursor = mydb.cursor()
            idkat = self.lineEditid.text()
            sql = "DELETE FROM product WHERE id =%s"
            val = (idkat, )
            cursor.execute(sql, val)
            mydb.commit()
            self.label_6.setText("Data Product Berhasil Diubah")
            self.lineEditid.setText("")
            self.lineEditbarkode.setText("")
            self.lineEditname.setText("")
            self.lineEditkategori.setText("")
            self.lineEditqty.setText("")
            self.lineEditharga.setText("")
        except mc.Error as e:
            self.label_6.setText("Data Product Gagal Diubah")

    def searchingproduct(self):
        try:
            keyword = self.lineEditsearch.text()
            mydb = mc.connect(
                host="localhost",
                user="root",
                password="",
                database="db_penjualanbaru"
            )
            cursor = mydb.cursor()
            sql = "SELECT * FROM product WHERE id LIKE %s OR name LIKE %s OR kategori LIKE %s"
            val = tuple(f"%{keyword}%" for _ in range(3))
            cursor.execute(sql, val)
            result = cursor.fetchall()
            if not result:
                self.label_6.setText("Data Product Yang Dicari Tidak Ada")
                self.tableWidget.setRowCount(0)
                return
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))
                self.label_6.setText("Data Product Yang Dicari Ditampilkan")
        except mc.Error as e:
            self.label_6.setText("Terjadi Kesalahan Saat Mencari Data")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "TextLabel"))
        self.pushButtonSearch.setText(_translate("Form", "SEARCH"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "BARKODE"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "NAME"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "KATEGORI"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "QTY"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "HARGA"))
        self.labelid.setText(_translate("Form", "ID"))
        self.labelbarkode.setText(_translate("Form", "BARKODE"))
        self.labelname.setText(_translate("Form", "NAME"))
        self.labelkategori.setText(_translate("Form", "KATEGORI"))
        self.labelqty.setText(_translate("Form", "QTY"))
        self.labelharga.setText(_translate("Form", "HARGA"))
        self.pushButtonInsert.setText(_translate("Form", "INSERT"))
        self.pushButtonUpdate.setText(_translate("Form", "UPDATE"))
        self.pushButtonDelete.setText(_translate("Form", "DELETE"))
        self.pushButtonLoad.setText(_translate("Form", "LOADDATA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
